CREATE TABLE IF NOT EXISTS customer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    type VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS real_customer (
    id BIGINT PRIMARY KEY,
    family VARCHAR(255) NOT NULL,
    FOREIGN KEY (id) REFERENCES customer(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS legal_customer (
    id BIGINT PRIMARY KEY,
    fax VARCHAR(20),
    FOREIGN KEY (id) REFERENCES customer(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS deposit (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    amount DOUBLE NOT NULL,
    customer_id BIGINT NOT NULL,
    version BIGINT NOT NULL,
    currency ENUM('EUR', 'USD'),
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE
);